spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: hadoop102:9092
